### PR TITLE
Hint Prob12 part 3

### PR DESCRIPTION
**Pull request by mauryaakanksha**

### CODE REVIEW

**Comment by zhenzhai** [comment]
Please fix your get_problem function. The returned string is not correct. Please see the tutorial video on how to find the correct problem type and problem name.

**Comment by mauryaakanksha** [comment]
Hi Zhen,

I changed the get_problem function.

Thanks,
Akanksha

**Comment by zhenzhai** [comment]
I'm having trouble understanding your hint. "What is the number 2 heads in 4 coin flips?" Do you mean "the number of different ways to have 2 heads"?

**Comment by mauryaakanksha** [comment]
Yes. I meant the number of different ways to get 2 heads in 4 coin flips. I
will change it.

**Pull request merged**
